### ISSUE TITLE
Player Statistics

### ISSUE THREAD

**Issue by MadTurt1e** [MadTurt1e/PicturePoker#10]
A database can be used to track how many wins and losses the player has achieved. 

Other statistics can be tracked as well: 

- lacement (Not just wins and losses)
- average coin count during victory
- average player habits
- Luigi’s difficulty per game
- etc

A statistics page can be implemented for players to look upon their former glories.  

This is a database heavy section.

**Comment by MadTurt1e** [comment]
I can see this being pretty straightforward to implement at this stage
```java
@GetMapping("/getStats/{playerName}")
    public String getStats(@PathVariable("playerName") String playerName) {
}
```
can be used, and this returns a string that is all the player statistics one may want to implement. 

Of course, we can shape this up with all the springboot madness in the future, but at our stage of the game, this is all that is really needed.

**Comment by jeffreyw2025** [comment]
Please update me with any statistics you want to see for the next checkpoint! For now I will consider statistics done.

**Comment by jeffreyw2025** [comment]
I think I have a few ideas for statistics so that the profile looks a bit less barren- namely the number of hands of each type a player managed to achieve and a number of cards cycled out per hand played. This will require some additional columns in the database and some game logic changes- I'll add those once the PR #39 is merged in.
